Better: [Customer SLA Indicator] Granularity by Category in Sources API Doc. RD-25403
ringcentral/engage-digital-api-docs pull request #130
Opened 2023-02-21 11:39 UTC by jmvallet

Cf. https://jira.ringcentral.com/browse/RD-25403

I updated reference spec (engage-digital_openapi3.yaml) and generated engage-digital_postman2.json with spectrum.

2023-02-23 11:32 UTC, DrissTM requested changes
minor suggestions

2023-02-23 11:32 UTC, DrissTM commented on specs/engage-digital_openapi3.yaml
> +        - description: Filtering strategy for Customer SLA indicator
```suggestion
        - description: Categories filtering strategy for Customer SLA indicator

```

2023-02-23 11:32 UTC, DrissTM commented on specs/engage-digital_openapi3.yaml
> +          description: Filtering strategy for Customer SLA indicator ("ignored_categories" or "selected_categories")
```suggestion
          description: Categories filtering strategy for Customer SLA indicator ("ignored_categories" or "selected_categories")

```

2023-02-23 14:04 UTC, jmvallet commented on specs/engage-digital_openapi3.yaml
> +        - description: Filtering strategy for Customer SLA indicator
It's updated, thanks

2023-02-24 09:20 UTC, DrissTM approved these changes
LGTM :+1:

2023-02-27 13:29 UTC, merged