api: add variables to endpoint url of openapi spec, fixes #19
ringcentral/engage-digital-api-docs pull request #21
Opened 2021-02-17 11:21 UTC by nel

Make variables url follow openapi spec for better website generation #19

2021-02-17 12:02 UTC, nel commented
@CedricBm I am not sure whether i should assign you to PR or simply add you as reviewer so i did both. I assign myself in another PR and got 0 mail but maybe it came from the 'myself' part.

2021-02-17 14:52 UTC, CedricBm requested changes
I received the email notification as soon as you made me reviewer 

> @nel requested your review on: #21 api: add variables to endpoint url of openapi spec, fixes #19.

And I also received the assignation email notification

> Assigned #21 to @CedricBm.

2021-02-17 14:52 UTC, CedricBm commented on specs/engage-digital_openapi3.yaml
> +        description: your own account name used as subdomain, it's the same as in the url of the engage digital service.
We seem to always begin our description with a capital letter :)

```suggestion
        description: Your own account name used as subdomain, it's the same as in the url of the engage digital service.
```

2021-02-17 14:52 UTC, CedricBm commented on specs/engage-digital_openapi3.yaml
> +        default: domainname
To make it extra clear that hyphens are allowed.

```suggestion
        default: domain-name
```

2021-02-17 14:52 UTC, CedricBm commented on specs/engage-digital_openapi3.yaml
> +        description: Depending on environment the base hostname is changing. In production it's api.digital.ringcentral.com for NA customers and api.engagement.dimelo.comfor historical customers. It'
```suggestion
        description: Depending on environment the base hostname is changing. In production, it's api.digital.ringcentral.com for NA customers and api.engagement.dimelo.com for historical customers. It's the same base hostname as in the url of engage digital service.
```

2021-02-17 14:52 UTC, CedricBm commented on specs/engage-digital_openapi3.yaml
> +  - url: 'https://{account_name}.{platform_hostname}/1.0'
Should we rather hardcode the `api` part here?

```suggestion
  - url: 'https://{account_name}.api.{platform_hostname}/1.0'
```

2021-02-18 13:03 UTC, CedricBm commented on specs/engage-digital_openapi3.yaml
> +        default: api.engagement.dimelo.com
If you agreed on the `.api` hardcoded in the url, then you can remove it from here. Also from the description.

2021-02-19 11:01 UTC, CedricBm commented on specs/engage-digital_openapi3.yaml
> +  version: '1.01'
Is this change expected? If so, shouldn't it be `1.0.1` or `1.1`?

2021-02-19 11:02 UTC, CedricBm commented
One last comment about the version, then lgtm

2021-03-05 13:14 UTC, merged