Feature: update docs for Apple Business Chat List Picker sections validations. RD-19050
ringcentral/engage-digital-api-docs pull request #54
Opened 2021-11-18 07:24 UTC by alexeevit

In RD-19050 we extended the sections validation from WhatsApp List Message to ABC List Picker to make it more consistent and stable. This MR is to update the ABC API limits documentation.

2021-11-18 17:51 UTC, DrissTM requested changes

2021-11-18 17:51 UTC, DrissTM commented on docs/interactions/structured-messages/select.md
> +| **`structured_content.items.section_identifier`** | String | **Optional if there's no sections**. The identifier of the section where the item is.<br>If there's no sections, the section_identifier
```suggestion
| **`structured_content.items.section_identifier`** | String | **Optional if there's no section**. The identifier of the section where the item is.<br>If there's no section, the section_identifier field should be removed.<br>Each section must have at least 1 item.<br>Limited to 200 characters. |
```

2021-11-19 09:09 UTC, alexeevit commented on docs/interactions/structured-messages/select.md
> +| **`structured_content.items.section_identifier`** | String | **Optional if there's no sections**. The identifier of the section where the item is.<br>If there's no sections, the section_identifier
fixed in 2 places

2021-11-19 10:04 UTC, DrissTM approved these changes
LGTM :+1:

2021-11-19 10:06 UTC, merged